name: Netsuite Deployment
run-name: ${{ github.actor }} is running the Netsuite Deployment
on: [push]
jobs:
  netsuite-deploy:
    runs-on: ubuntu-latest
    environment: netsuite-demo
    steps:
      - name: Check out repository code into runtime
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
      - name: Install Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Install SuiteCloud CLI
        run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense
      - name: Setup Credentials File
        run: |
          mkdir -p ~/.suitecloud-sdk
          echo "${{ secrets.CREDENTIALS_P12 }}" | base64 -d > ~/.suitecloud-sdk/credentials_ci.p12
          ls -la ~/.suitecloud-sdk/
      - name: Debug
        run: |
          echo "Passkey length: ${#SUITECLOUD_CI_PASSKEY}"
          pwd
          ls -la
          cat project.json
        env:
          SUITECLOUD_CI_PASSKEY: ${{ secrets.PASSKEY }}
      - name: Validate Project
        env:
          SUITECLOUD_CI: 1
          SUITECLOUD_CI_PASSKEY: ${{ secrets.PASSKEY }}
        run: suitecloud project:validate
      - name: Deploy Project
        env:
          SUITECLOUD_CI: 1
          SUITECLOUD_CI_PASSKEY: ${{ secrets.PASSKEY }}
        run: suitecloud project:deploy